# See https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates for more information about this file.

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
